spring.application.name=console-shop-api

spring.datasource.url = jdbc:postgresql://localhost:5432/console_shop
spring.datasource.username = postgres
spring.datasource.password = postgres
spring.jpa.hibernate.ddl-auto = none
spring.jpa.show-sql = true
logging.level.org.springframework.web = DEBUG
